import os
import sys
import uuid
from dotenv import load_dotenv
from sqlalchemy.orm import Session

# Add project path so we can import our models
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

load_dotenv()

import database
import models
from tts_service import text_to_speech

# ════════════════════════════════
#        STORIES DATA
# ════════════════════════════════

stories = [
    # Level 1 — Stories 1-20 (simple, ages 6-7)
    {"id": 1,  "level": 1, "title": "Kitten's Choice",         "content": "Kitten plays with her new toy. She loves her new toy. Her brother likes her new toy, too. When Kitten isn't playing with it, her brother takes it to play. Kitten is having fun. Then, she sees a mouse! She wants to chase the mouse. If she chases the mouse, her brother will take her toy. Kitten thinks. She can only choose one thing to play with. If she picks the mouse, her toy will go away with her brother. If she picks the toy, the mouse will run away. Which one should Kitten pick? Kitten runs after the mouse. She does not see a lot of mice, so that is more fun. She does not catch the mouse, but she has fun running after him. Kitten is happy with her choice."},
    {"id": 2,  "level": 1, "title": "Dessert Time!",           "content": "Yum! It is time for dessert. First, Tim gets a cookie. Next, Jan gets some cake. Then, Ben gets a donut. Last, Deb gets some pie. Oh no! There is none left for Sam. What will he do? First, Tim shares his cookie. Next, Jan shares her cake. Then, Ben shares his donut. Last, Deb shares her pie. Yum! Sam and his friends are happy. It is time for dessert."},
    {"id": 3,  "level": 1, "title": "A Cold Bear",             "content": "Brrrr! It is getting cold. Bear needs to get ready for winter. First, he eats a lot. Next, he finds a den. Then, he fills the den with leaves, so he will stay warm. Last, he eats even more! Is Bear ready for winter? Yes, he is. Winter is here!"},
    {"id": 4,  "level": 1, "title": "At the Zoo",              "content": "First I saw the white bear, then I saw the black. Then I saw the camel with a hump upon his back. Then I saw the grey wolf, with mutton in his maw. Then I saw the wombat waddle in the straw. Then I saw the elephant a-waving of his trunk. Then I saw the monkeys, mercy, how unpleasantly they smelt!"},
    {"id": 5,  "level": 1, "title": "Blanket Adventures",      "content": "Jake liked to pretend. He draped a blanket over his shoulders. The blanket turned into a robe. Jake had become a king! Jake asked his mom to make waffles for breakfast. He did not think kings ate oatmeal. Jake grew tired of being a king. He laid the blanket out flat on the floor. The blanket turned into a magic carpet. Jake made swishing sounds as if he was flying. Jake landed his magic carpet. The blanket turned into an island in the sea. Jake's cat became a sea monster! After the battle, Jake grew hungry. He draped the blanket between two chairs to make a tent. Jake asked his mom to cook hot dogs for lunch. After eating the hot dogs, Jake grew tired of camping. The blanket turned into a cape. Jake became a superhero! Jake found his sister reading a book, but she did not want to be rescued. Jake felt a tug on his cape. His dog Bandit had grabbed the end of Jake's blanket. The blanket turned into a rope in a game of tug-of-war. Jake grew tired, climbed into bed and took a nap."},
    {"id": 6,  "level": 1, "title": "The New Bicycle",         "content": "Emma has a new bicycle. It is bright pink and shiny. It was a gift from her uncle. He hid it behind a bush to surprise her. When Emma looked behind the bush and saw the bicycle, she jumped for joy. It was just what she wanted. She gave her uncle a big hug. She loves her new bicycle, and she loves her uncle."},
    {"id": 7,  "level": 1, "title": "Penny's Pet Problem",     "content": "More than anything in the world, Penny wanted a pet. She thought of asking for a puppy. She thought of asking for a kitten. She thought of asking for a hamster. Above all else, Penny knew she wanted a pony. One morning, Penny dared to ask her mom for a pony. You don't see many ponies living in apartments, Penny's mom said. Besides, a pony needs a place to sleep. I could share my bed with him, Penny said. I don't think so, Penny's mom replied. What if your pony kicked off all the blankets. Besides, a pony needs a place to eat. He could eat at the table with us, Penny said. I don't think so, Penny's mom replied. What if your pony had poor table manners? Besides, a pony needs a place to spend time outside. He could spend time on our balcony, Penny said. I don't think so, Penny's mom replied. We live on the fourth floor. What if your pony is afraid of heights? So, I guess this means I can't have a pony, Penny said. It means we can't keep a pony in our apartment, Penny's mom replied. But I know where we can visit some ponies."},
    {"id": 8,  "level": 1, "title": "A Puzzle a Day",          "content": "Anna and her family love doing puzzles. Anna is best at little puzzles. Anna and her brother work on medium size puzzles together. Anna's brother likes puzzles with cars in them. When the whole family does a puzzle, they do really big puzzles. It can take them a week to finish a really big puzzle. Last year they did a puzzle with 500 pieces! Anna tries to finish one small puzzle a day by herself. Her puzzles have about 50 pieces. They all glue their favorite puzzles together and frame them. The puzzles look so nice on the wall."},
    {"id": 9,  "level": 1, "title": "The Thunderstorm",        "content": "The kids were outside playing catch. They heard a rumble in the sky. They didn't want to stop playing, but they knew it wasn't safe to be out in a storm. Also, they did not want to get wet. They decided to go inside and play a board game. They loved listening to the thunder as they played their game. The kids went outside again after the storm had passed. They saw a rainbow!"},
    {"id": 10, "level": 1, "title": "A Visit to the Water Park","content": "There is a new water park in town. We go there on the first day of summer. It has pools and water slides. There are sprinklers too. The slides are scary at first. After the first ride, we love the water slides. The sprinklers are cool on hot days. One of the pools makes its own waves. All the kids try to surf the waves. It is really fun. The water park can be very crowded. There are many kids and adults, but they do not allow pets. We really like the ice cream at the snack bar. They also sell pop and donuts. We all love the new water park."},
    {"id": 11, "level": 1, "title": "Making Cookies",          "content": "Greg likes to help his mom make cookies. Chocolate chip cookies are his favorite. His mom likes them too. He adds the chocolate chips to the batter. Then he stirs them in. He forms the batter into balls and places them on a baking sheet. His mom places the baking sheet into the oven. When the cookies are in the oven, Greg licks the last bits of batter from the bowl. He can hardly wait for the cookies to be ready. In 30 minutes the cookies are finished baking. The cookies are hot and yummy."},
    {"id": 12, "level": 1, "title": "Mule's Thoughts",         "content": "A silly little mule sat on a milking stool and tried to write a letter to his father. But he couldn't find the ink, so he said: I rather think this writing letters home is too much bother."},
    {"id": 13, "level": 1, "title": "Monster Learns Rules",    "content": "One day, a monster came to our classroom. He didn't know any of the rules! We had to show him how to sit on the carpet. We had to show him how to use a quiet voice. We had to show him how to use supplies. We went to P.E. class. Monster tried to sit on the carpet. No, Monster! We don't have to sit on a carpet in the gym! Monster tried to use a quiet voice. No, Monster! We don't have to be quiet in the gym. Monster didn't know what to do with the supplies. We showed him how to throw a ball. We went to the lunchroom. Monster sat at a table. Good job, Monster! Monster used a loud voice. No, Monster! We can't be too loud in the lunchroom. Monster tried to throw his food. No, Monster! We can't throw food. Monster was confused. Poor Monster. We went to our classroom. We wrote the rules for the different places at school. Rules are different in different places. It is tricky but it keeps us safe!"},
    {"id": 14, "level": 1, "title": "All About Bears",         "content": "There are many kinds of bears. Some bears live in warm places, like sun bears. Some bears live in cold places, like polar bears. Bears are different colors, too. They can be white, brown, or black. Some bears eat plants. Some bears eat animals. Bears have long snouts, or noses. They have claws and fur, too. Baby bears are called cubs. When it gets cold, bears sleep in dens for the winter. Dens can be in trees or caves. When they are sleeping all winter, it is called hibernating. Bears do not eat when they are hibernating."},
    {"id": 15, "level": 1, "title": "The Puppy and the Kitten","content": "My family just adopted a puppy and a kitten from the animal shelter. They were so young, they did not even have names yet. We had to think of good names for them. The puppy likes to jump up. The kitten likes to curl up in our laps. What do you want to name them? asked Mom. My sister said, Pounce for the puppy and Cuddles for the kitten. We all thought those names were perfect."},
    {"id": 16, "level": 1, "title": "The Boat Parade",         "content": "The boats are floating along the lakeshore. It is the summer boat parade. There are motorboats, rowboats and sailboats. Jessica's favorite is the yellow motor boat with the flag. The rowboat decorated with flowers is Lisa's favorite. Tony likes the purple sailboat. The boats float by one at a time. The people on the boats wave at the crowds. The crowds cheer the boats. The boat parade is so much fun to watch. It is the best part of the summer."},
    {"id": 17, "level": 1, "title": "Peanuts and Popcorn",     "content": "John is going to a baseball game with his aunt. He can't wait to get there. It is the first game of the season. The stadium is almost full. He loves to watch baseball, but his favorite part of going to games is eating the snacks. There are many different snacks at baseball games. A man in a red hat walks up and down the aisles selling peanuts and popcorn. Guess which is John's favorite. John likes them both. He especially likes mixing peanuts and popcorn together. If he is really hungry he will have a hot dog."},
    {"id": 18, "level": 1, "title": "Shoveling Snow",          "content": "I want a new toy. Mom says toys cost money. How can I get money? I look outside. There is a lot of snow! Mom says I can earn money if I shovel our driveway. I do. It is fun! I do not have enough money for my new toy. I look around. Mrs. Jen has a shovel. Can I shovel her driveway? She says yes! I almost have enough money for my new toy. Mr. Tom has a shovel. Can I shovel his driveway? He says yes! I can get my new toy!"},
    {"id": 19, "level": 1, "title": "Homework or Video Games", "content": "Brad loves to play video games. His favorites are Disney games. Brad got home from school one day, and his mom asked him if he had homework. He did, but he thought about saying no because he wanted to play his games. Then he changed his mind. He knew that if he lied, he would lose his games for a week. He did his homework first and still had time to play two games before dinner. He knows it is best to be honest."},
    {"id": 20, "level": 1, "title": "Apples",                  "content": "Do you like apples? Apples can be red, yellow, or green. Each color tastes different. They are fruit. You can make apples into treats. Apples grow on trees. They finish growing in the fall. Then you can pick them to eat. When you pick an apple, you twist it and then pull it off the tree. There are five parts of an apple. The outside is the skin. The inside is the flesh. There are seeds inside of the apple. The stem is on top. Some apples have leaves by the stem. What else do you know about apples?"},

    # Level 2 — Stories 21-40 (medium, ages 8-9)
    {"id": 21, "level": 2, "title": "How to Catch a Cookie",   "content": "Tommy woke to the sound of shouting and running feet. A big man in a long white apron ran past him shaking a wooden spoon in the air. Come back here! the man yelled. He seemed very upset. I am Chef Shiraz and I bake the best cookies you'll ever taste, if you can catch one. The spice in my recipe gives them the snap to jump right off the pan once they're cooked. What if you locked the bakery doors before you took the pan out of the oven? What if you wrapped licorice around their legs before you put them into the oven? I believe licorice will melt in a hot oven. What if you used a heart shaped cookie cutter for your gingerbread? Tommy opened his eyes to find his mother gently shaking him. Wow Mom! You're never going to believe the dream I just had."},
    {"id": 22, "level": 2, "title": "Alien Money",             "content": "Zander was hard at work growing food for himself and his neighbors. He heard a knock at his door. It was his neighbor Jules. She was holding some cleaning products. Hi, Zander. I just finished making some cleaning products. Do you need any? Can I get some cleaning spray? I can give you 4 breakfast plants for a bottle. I have enough breakfast plants for this week. How about 4 lunch plants? They need a couple more hours to grow before I can give them to you. Jules knew she could trust Zander, so she left the cleaning spray with him and went home. I wish there was an easier way to get and give our items. Trading isn't always easy. Sometimes I don't have enough plants ready to trade. Jules agreed. They went home thinking and wishing for a way to make their lives easier."},
    {"id": 23, "level": 2, "title": "Cardboard Town",          "content": "Fine, I'll just do it all myself! I thought as I stomped away. My friends and I were trying to make the best cardboard town to play in. We had boxes that we were turning into stores and playgrounds and all sorts of other fun things! Wow, I didn't think he'd get so mad, Katie said. This was supposed to be fun, said Max. Johnny can't do it all by himself. I realized that it was just too big of a job. I couldn't make the buildings out of boxes, and put them around the town, and decorate them all by myself. I guess that's why people work together. The next day at school I said sorry to Katie and Max. Will you come back to my house today to complete our town? Sure, Johnny, they said. We all took on a role and the town was done in no time. It was great!"},
    {"id": 24, "level": 2, "title": "Playing Catch",           "content": "Kate and her brother Jake like to play catch. They play with softballs, footballs and tennis balls. They toss the balls back and forth in the yard all the time. Sometimes they go to the park to have more space for throwing the balls farther. When it is raining out, they play catch in the basement. They use a tennis ball because it bounces off of the basement walls. Jake is going to soccer camp for a week this summer. Kate is sad because she won't have anyone to play catch with while he is gone. The week before Jake leaves, they go to the park together. There is a girl tossing a ball in the air by herself. Kate and Jake invite her to play with them. Her name is Brooke. Kate is happy now that she has a new friend to play catch with while her brother is at camp."},
    {"id": 25, "level": 2, "title": "Sly's Secret Adventure",  "content": "Sweet dreams, Mom whispered as she tucked Erin into bed. Sly will watch over you through the night. The cat began to purr. Sly waited as Erin's eyes closed and she drifted off to sleep. Only then did he slide off the bed and snuck down the stairs on silent paws. Sly sat down beside his food dish and stirred the dry kibble with his paw. His tummy grumbled. He walked over to the kitchen pantry. On the third try the door opened. Sly spied a bag of cat treats. On his third try a bag of pepper dropped from the shelf. Sly sneezed and walked away flicking his tail. In the family room, Sly saw it, a real mouse! Off Sly dashed across the room. The mouse dove under a bookcase. Sly lunged and hit his head as the mouse escaped. Sly shook his head and walked away. Sly sneaked up the stairs on silent paws. Good morning Sly, Erin whispered. I always have sweet dreams with you beside me. The cat purred."},
    {"id": 26, "level": 2, "title": "Going to the Movies",     "content": "My class is going to the movies on a field trip next week. We have to get permission slips signed before we go. We are going to see a movie that tells the story from a book we read. We love it when movies are made from books. It is fun to compare the movie to the book. I usually like the book better. We get to the movie early so we can buy popcorn. Some of us buy candy and slushes too. We all enjoy watching the movie. When we return to school, we talk about things that were in the movie and the book. The movie and book are similar. We all agree that we like the book better though. Books let you picture the characters any way you want to picture them."},
    {"id": 27, "level": 2, "title": "Dave and Grant Love Kayaking", "content": "Dave and his friend Grant love to go kayaking in the summer. They each have their own kayak. Dave's kayak is yellow, and Grant's kayak is red. Whenever it is not raining, they kayak on the small lake in town. They look for fish, turtles and muskrats when they are kayaking. They also like to see ducks and loons. Sometimes they bring fishing poles with them so they can try to catch fish. They have the most fun when they race each other in their kayaks. They always pack a lunch. They have a favorite spot on the lake to stop and eat their sandwiches. After lunch, they paddle around the lake some more. Then they stop again to have some cookies. They really love kayaking."},
    {"id": 28, "level": 2, "title": "The Clean Park",          "content": "Tyler asked his mom if he could ride his bike to the park. As long as you wear your helmet when you are riding, she said. When Tyler got to the park it was filled with people holding garbage bags. A lot of his friends were there and so were some of his teachers. His friend Bella said, Everyone is pitching in and cleaning the park today. She asked Tyler if he would help. Tyler said, Sure, and asked for a garbage bag. There was garbage everywhere. After an hour, he had filled three garbage bags. When everyone was finished, one of the teachers loaded the filled garbage bags into his pick-up truck. The park looked great. The teachers bought pizza and lemonade for everyone who helped clean the park. After they ate, Tyler and his friends made sure to put their garbage into the garbage cans."},
    {"id": 29, "level": 2, "title": "Taking the Chill Out",    "content": "Mia likes animals. She likes all kinds of animals, even the ones other people think are ugly. Every summer, Mia and her dad have a lot of fun together at the zoo. One frosty morning, after the first snow fall, Mia got a surprise. Mia's dad asked her if she wanted to go to the zoo. But it's cold outside Dad, Mia said. Won't the animals be inside? It's not that cold, her dad replied. Lots of animals will be outside. At the zoo, Mia watched a lion stretched out on a big rock. His keepers use a heating pad to help him stay warm, her dad said. The heating pad is hidden inside the fake rocks that the lion is lying on. Mia watched the otters play in their pool. Their keepers heat the water to help them stay warm. Mia slid on a patch of ice as she stopped at the giraffe enclosure. She looked but couldn't see any of the big animals. Oh, I get it Dad, Mia said and laughed. The giraffes need winter boots. That's pretty smart, Dad said."},
    {"id": 30, "level": 2, "title": "Don't Give Up",           "content": "If you've tried and have not won, never stop for crying. All that's great and good is done just by patient trying. Though young birds, in flying, fall, still their wings grow stronger. And the next time they can keep up a little longer. Though the sturdy oak has known many a blast that bowed her, she has risen again, and grown loftier and prouder. If by easy work you beat, who the more will prize you? Gaining victory from defeat, that's the test that tries you!"},
    {"id": 31, "level": 2, "title": "The Camping Trip",        "content": "Lily and her brother Ryan went camping with their mom and dad. Ryan and Dad set up the tent while Lily and Mom collected sticks to start a bonfire. Once the tent was set up, they started a fire in the bonfire pit. Lily and Ryan looked for long pointy sticks to use for cooking hot dogs over the fire. They found four perfect sticks, one for each of them. Lily and Ryan, and their mom and dad, each placed two hot dogs on their sticks. They held the hot dogs over the fire and turned the sticks slowly so every side of each hot dog was cooked. Then they put the hot dogs into buns and added ketchup and mustard. The hot dogs were delicious. After they all enjoyed their hot dogs, Lily got out the marshmallows for dessert. They all roasted marshmallows over the fire until the marshmallows turned a nice shade of brown. Sitting around the bonfire and eating marshmallows is Lily and Ryan's favorite part of camping."},
    {"id": 32, "level": 2, "title": "Giving",                  "content": "Shari was so excited for her birthday. She thought about the fun party she was going to have and the presents she would get. But, her mom told her that she had to make room for new toys by choosing some old toys to give away. Shari was not happy. She loved all of her toys! Her mom sat down with her in front of her toy chest. They looked through the toys one at a time. When they were finished, there was a very large keep pile, and some toys in the donate and maybe piles. They went to a place where kids lived who didn't have homes, and asked the workers if they could hand out toys. Seeing the kids' smiles made Shari so happy. Shari turned to her mom and asked if they could get the maybe bag out of the car. The other kids needed those toys more than she did! Shari felt so great that her choice made the other kids so happy."},
    {"id": 33, "level": 2, "title": "Guitar or Ballet",        "content": "Emma loves to listen to her brother Jake play his guitar. He is 15 years old and has been playing since he was 5 years old. He practices every day, and he is really good. He plays country music and rock and roll. Emma likes the country songs best. Emma wants to take lessons so she can play as well as Jake does. Mom, can I take guitar lessons? Emma asks. Her mom replies, It takes a lot of hard work to play the songs that Jake plays. Are you sure you have enough time to put into practicing? Thinking about all of her favorite activities, Emma isn't sure. She loves her ballet classes, her art classes and her chess club. Emma realizes that if she wants to play guitar, she will probably have to give up another activity. Emma decides that she will just keep enjoying her brother's guitar playing for now."},
    {"id": 34, "level": 2, "title": "Pen Pals",                "content": "We are learning how to write friendly letters at school. I don't mind writing practice letters, but it would be more fun to write a real letter to someone. Our teacher, Mrs. Snow said that we really are going to write a letter to someone! She said we are going to write to second graders in England to see what life is like there. My pen pal's name was Oliver. The only things Mrs. Snow said we had to include in our letter were two questions. Which holidays do you celebrate during the year? What do you like to play? It took a few weeks, but the day we got letters back from our pen pals was an exciting one! Oliver plays video games like we do over here. One holiday they celebrate that I don't is Boxing Day. It was interesting to see what is the same and what is different about living in different countries."},
    {"id": 35, "level": 2, "title": "Playground",              "content": "Molly and her friend Bella were playing at the playground. They were supposed to be taking turns on the swing. Molly counted to 100 while Bella was on the swing. Bella didn't get off the swing. Bella! I counted to 100, it's my turn! said Molly. You counted too fast, it's still my turn, Bella said. Molly was upset. She wanted a turn on the swing, too! Molly could tell the teacher, but her teacher always wanted them to try to solve the problem first. She decided to try using an I message. That means to tell the other person how you're feeling, why you feel that way, and what they can please do to make it better. Bella, I feel sad because we were supposed to take turns after 100 seconds. Will you please get off? Molly asked. Finally, Bella got off the swing. Molly was happy because she solved her problem all by herself!"},
    {"id": 36, "level": 2, "title": "Springtime Tadpoles",     "content": "Every spring, Max and his brother Will go to the pond at the end of their street to look for tadpoles. They love to catch them so they can watch them turn into frogs. This spring when Max and Will go to the pond to catch tadpoles, they see a painted turtle sitting on a log enjoying the sun. Should we try to catch it? Max asks. Will responds, I like catching tadpoles better. Max agrees with Will. They fill their bucket with tadpoles and head home. They cover the tub with a screen so animals can't get to the tadpoles. They keep the tub in the shade so the water does not get too hot. Max and Will go to the pond every day to bring back fresh water and leaves from the bottom of the pond for the tadpoles to eat. After six weeks, the tadpoles grow into frogs. Then Max and Will take them back to the pond so they can live happily ever after."},
    {"id": 37, "level": 2, "title": "Grandpa's Cooking",       "content": "Ella loves her grandpa. He lives in Texas and comes to visit once a month. She wishes he came to visit every week because he tells great stories and makes her favorite dinner. Ella asks her mom to make the barbeque chicken that Grandpa makes. Ella's mom says, I will try, but no one makes it as well as Grandpa does. Ella watches her mom prepare the sauce for the chicken. It looks tasty. When the chicken is finished cooking, Ella's family sits down to eat. Her mom was right; no one makes the barbeque chicken as well as Grandpa. The next time her grandpa comes to visit, Ella tells him the story about her mom trying to make the chicken. Her grandpa says, That is a great story. Then he teaches Ella and her mom how to make the chicken. Ella and her mom make the barbeque chicken once a week. It still does not taste quite as good as Grandpa's. Ella loves her grandpa."},
    {"id": 38, "level": 2, "title": "Race Cars",               "content": "Zoom! Zoom! Zoom! The race cars were all practicing for the big race tomorrow. Around and around and around the track they went. They practiced weaving in and out of cones, going around the curves, and starting right when the green light went on. Blue Race car and Red Race car were best friends, so they practiced together all day. That night, they were in the garage resting up for the big race tomorrow. Red Race car couldn't sleep, though. Blue Race car, are you asleep? Red Race car asked. No. I'm feeling nervous for the race tomorrow. How are you feeling? Blue Race car answered. I'm feeling nervous, too. We could try taking deep breaths. Ready? We'll breathe in and count to three. Then we'll keep the breath in for three seconds. Last, we'll slowly let all of our breath out. They took some slow, deep breaths together. After a few minutes, both race cars started to feel calm, and drifted off to sleep."},
    {"id": 39, "level": 2, "title": "The Washing Machine Box", "content": "Sarah's family's washing machine stopped working, so her dad ordered a new one. It was going to be delivered on Saturday. When Saturday came, Sarah and her friend Emily sat in the front yard waiting for the delivery. They were excited because they knew that they would get to play with the box. Big boxes are so much fun, said Sarah. Emily agreed and said, We can make the box into whatever we want. As soon as the washing machine was out of the box, Sarah and Emily took out some crayons and colored all over it. They turned it into a pink, red, blue and yellow clubhouse. It was their clubhouse for a while, and then it was a fancy car. After that, they cut out a square on one side and made it into a TV. They acted out their favorite TV shows for the rest of Sarah's family. It was a fun day for everyone."},
    {"id": 40, "level": 2, "title": "Sharks",                  "content": "What has fins, sharp teeth, and swims in the ocean? A shark! Sharks have been around for a very long time. Sharks have lived in the oceans even before dinosaurs roamed the earth! Sharks are fish, and there are over 400 types of sharks. When they have babies, the babies are called pups. Sharks lose their teeth, like humans, but they don't just lose their baby teeth. They lose teeth throughout their lives. When a shark loses a tooth, a tooth from another row of teeth will move into its place. New teeth are always growing. Most sharks are carnivores, so they feed on other animals, like fish or seals. Sharks might look scary, but they are not usually dangerous to people. People are more dangerous to sharks, since people hunt sharks."},

    # Level 3 — Stories 41-60 (harder, ages 10-11)
    {"id": 41, "level": 3, "title": "After the Flood",         "content": "Reading about weather in books is one thing, but living through a natural disaster was another. Even though the flood was not too bad, I was not prepared for what it was really like! It all started two days ago. It was a rainy day, like every other rainy day. The only unusual thing was how anxious the adults seemed to be getting. The meteorologists kept saying that the rain hadn't stopped in a long time. I woke up and went down for breakfast. I went to get out the milk, but there was a note on the refrigerator telling me not to open the door. I noticed that I could hear noises coming from the basement. I went to investigate. There was water down there! Good morning, Vicky. All of this rain is causing some problems. The power all over town is out. Our basement is flooded, and so are some of the roads. We pumped the water out by hand, but there's some damage downstairs. We decided to drive around to see how other people in our town were doing. We stopped to help people who were filling bags with sand. The bags helped to keep the water away. I can't believe those people lost all of their clothes and household items. We should go through our stuff and see what we can donate. We're lucky we only had a couple of inches of water in our basement, it could have been a lot worse."},
    {"id": 42, "level": 3, "title": "Alex and Amanda's First Concert", "content": "The most popular teen band was coming to town, and both Alex and his twin sister Amanda really wanted to go to the concert. They had never been to a concert because their parents' rule was that you must be in sixth grade to go to a concert. Alex and Amanda were only in fifth grade. Please, Mom and Dad. We will do anything if you let us go, they begged their parents. Their mom and dad said they would think about it. After about a week's time, their parents brought the subject of the concert up at dinner. They said they would reconsider their rule with a couple of conditions. First, work very hard and get an A on your next book report. Second, pay for the concert tickets yourselves. Third, find a responsible adult to drive and go to the concert with you. Andrea, you could go with us. You are 18 years old which makes you an adult, and you are responsible. The day of the concert had arrived. It was the most amazing experience Alex and Amanda had ever had. On the drive home, Alex and Amanda thanked Andrea and Renee over and over again for taking them."},
    {"id": 43, "level": 3, "title": "The Astronomy Project",   "content": "Mrs. Lindsey was everyone's favorite teacher at Lincoln Elementary School. She was known for her entertaining teaching techniques. One day she walked into the classroom and announced to the class that they would all be seeing stars in their futures. Does anyone know what astronomy is? Olivia raised her hand and said, I'm a Libra. Astronomy is a branch of science that deals with celestial bodies, the universe as a whole and space. We are going to be learning about astronomy in this unit. I saw Ursa Minor, announced Andrew enthusiastically. It looks like a dot-to-dot ladle, said Olivia. Did you know that Ursa Minor is also called the Little Dipper because it looks like a ladle? Mrs. Lindsey explained that she would assign each student a constellation, and that they would each make a poster board illustration. She passed out one poster board and one glow-in-the-dark marker to each student. Mrs. Lindsey arranged the students around each other in a similar fashion to the way the constellations appeared on the constellation chart. Next she closed the blinds and turned off the lights. Awesome! We can all see each other glowing and moving around just like the stars do, the students said in unison."},
    {"id": 44, "level": 3, "title": "Best Friend Blues",       "content": "Alexa and Brittany were best friends. They'd known each other since Brittany moved next door in 2nd grade. They hung out almost every day after school. They were very different people. Alexa did great with her school work, read a lot of books, and took ballet classes. Brittany, on the other hand, would rather play soccer, chat with other kids at school, and rarely sat still for long enough to finish reading a chapter of a book. Come on, let's play on the equipment. We've played soccer for the last three days! Alexa said. They just cut the grass, I love playing soccer when the grass is nice and short. I don't want to play on the equipment, Brittany replied. We always do what you want to do Brittany, it's my turn to choose. Alexa was getting frustrated. Fine, go play on the equipment by yourself, I'm playing soccer, Brittany shouted. When it was time for lunch, Alexa hung back to talk with Mrs. Stone. Mrs. Stone, I have Brittany's notebook. Would you be able to help us solve our problem? At recess, Mrs. Stone sat and talked with the girls. Mrs. Stone helped them realize that maybe they didn't have to play together every day to be best friends. They decided to just play together a couple times a week, and take turns picking the activity."},
    {"id": 45, "level": 3, "title": "Bring Your Pet Day Disaster", "content": "I had my backpack on my back and a leash in my hand. It was Bring Your Pet to School day! My dog Jax was happily trotting beside me as we walked to the bus stop. The other kids in my neighborhood had their pets, too. Josie had a fish bowl with her beta fish. John had a crate with his cat, Maxie, inside. Paula had a bird cage with her parakeet, Gerald. Once we got on the bus, though, things started to go downhill. The bus was so noisy! The animals would not use their inside voices. And the smell was terrible! Another dog rushed up to us with a leash trailing behind her. She and Jax started to sniff each other curiously, and started to play. Fluffy! Get back here! I heard one of the third graders shout. Finally, we were at school. It looked like a zoo! There were animals everywhere! Some animals running free through the grass and on the sidewalks, with kids chasing them in every direction! I saw a kangaroo hopping in the grass! And a peacock strutting up the stairs! And I woke up, snug in my bed. Wow, no wonder our school doesn't have a Bring Your Pet to School day!"},
    {"id": 46, "level": 3, "title": "Dinner Disaster",         "content": "Ugh, meatloaf again? I hate meatloaf! Matt yelled. I'm not eating this. You know what, Matt? We're going to let you take over dinnertime from now on. You can pick the meals and cook them, as long as they're healthy, Mom said. The next day, Dad sat down with Matt to make the meal plan. We're going to have chicken tonight, and spaghetti tomorrow, and macaroni and cheese the next day, Matt started. What else are we going to have with the chicken? We need to have at least one vegetable with each meal. Oh, yeah. Um, we can have corn with the chicken, Matt said. Sophia does not like corn, said Dad. This is impossible! Matt said, exasperated. It took almost an hour to make dinner. There were so many steps! Matt was tired and extra hungry when dinner was finished. Ew, this rice tastes funny, Sophia said. I'm sorry, Sophia. I'm sorry, Mom and Dad. I shouldn't have yelled at you guys about dinner all the time. I didn't know how hard it was to pick out food everyone likes. Matt felt a lot better. He happily finished his dinner and never complained about a meal his parents made again."},
    {"id": 47, "level": 3, "title": "Fairy Followers",         "content": "Drawing is my passion. I draw the land around me, and lands I make up in my head. Whenever I leave a drawing there overnight, it disappears! I search everywhere for my drawings, but I can never find them! Tony, I need your help! My drawings keep disappearing. Can you help me spy on my desk overnight? I ask. Sure, sis. I think I might be able to set up my tablet to record video all night so we can see what's happening. We had seen fairies take my drawing! Four of them, one for each corner of the paper. Fairies! They picked up my paper, and a little door appeared right next to the window by my desk! I wonder if they can read, maybe we should leave them a note. The note says, Hi Fairies, We're Jamie and Tony. Why are you taking my drawings? We'd love to meet you! As the clock turns from 11:59 to 12:00, we see a light by my window. It's the door opening! Out fly the same 4 fairies that we saw on the camera! Suddenly, we're through the little fairy door, in a world like nothing we've ever seen."},
    {"id": 48, "level": 3, "title": "Fossil Mystery",          "content": "What is that? It looks like a fossil. It looks part-human. The archeologists all started talking at once. What if it's neither human nor animal? What if it's something we haven't discovered yet? Maybe even something from out of our world. Frank said, I think you might be right. It's not a dinosaur or any other animal we've encountered. The fossil was hard to describe. It was smaller than a human, but looked like it would have stood on two legs instead of four. Its head was large and it had 6 fingers on each hand, and 8 toes on each foot. Do you think it could have been a human from long ago? Frank asked. The next morning, I rushed straight to the fossil. The fossil was different. It had changed overnight! Now it looked like a small bear. When night fell, we set up a rotation to make sure two of us were with the fossil at all times. In the morning, I went by the fossil to again find my colleagues puzzling over the fossil. It had changed again! No one had seen or heard anything on their watch. To this day, no one has found the answer to the mystery."},
    {"id": 49, "level": 3, "title": "Mystery of the Broken Pie","content": "The sun was shining on the sparkling grass. It was morning, and the grass was still wet from the dew. Sydney and I were tired of being stuck inside. Mom, can we go out and play? I shouted. You and Sydney need to clean your rooms first. I'm excited to get some fresh air in the house, it's time for a good spring cleaning! Mom answered. We decided to make it a race to see who could clean their room the fastest. DONE! I heard Sydney shout from her room down the hall. Mom had all the ingredients out to make her famous apple pie. Make sure you stay in the yard, and if you play nicely, you'll get some pie in a few hours! she replied. When we got in the house, we could hear Mom vacuuming in the living room. Sydney and I walked to the kitchen to see if the pie looked ready. We peered up at the pie and gasped. It was a mess! The crust on top had holes in it, and the filling was all over the place. I bet that some birds smelled the pie and wanted a piece! It's right by the open window! Next to the pie, we saw the filling, and one small footprint. That looks like a bird footprint, right? I asked Sydney. She agreed. Well, what do you guys think about going out to get ice cream since the birds ate our pie? Yay!!! we shouted."},
    {"id": 50, "level": 3, "title": "The Best Vacation Ever",  "content": "Winter break was fast approaching, and all Scott wanted to do was go snowboarding. Unfortunately, Scott's parents had different plans. They had booked a weeklong tropical cruise. Scott hated warm weather and asked if he could just stay at his best friend's house so he could snowboard every day. His parents didn't want to hear anything of it. Family time was important to them, and it was tradition that they spend winter break together. When they arrived at the port to board the ship, Scott had a hard time admitting that he was actually impressed with the size of the ship. Then he remembered that the brochure said something about a surfing pool. Maybe surfing would be somewhat like snowboarding. After all, it involved riding a board. Scott's dad went first and only lasted about five seconds before he wiped out. When it was Scott's turn, he took a stance similar to his snowboarding stance. On his first ride, Scott rode for almost 30 seconds before wiping out. He was hooked. By the time the weeklong cruise was over, Scott had new friends, a new hobby, and great memories. He apologized to his parents for initial moaning and groaning, and told them it was his best vacation ever."},
    {"id": 51, "level": 3, "title": "Finders Keepers",         "content": "It was the middle of the day on a bright sunny Saturday, and Jay and his friends Mike and Tony were riding their dirt bikes on one of their favorite off-road trails. On this particular day, Jay and the boys were perched in one of their preferred trees when Jay spotted something shiny on the ground. What they found was incomprehensible to them. It was a gold money clip holding five hundred dollars. Mike immediately exclaimed, Awesome! We can split up the money! Not so fast, said Tony. Jay was the one who spotted the cash. To be fair, he should get more than us. What are you guys, crazy? asked Jay. We can't keep the money. It isn't ours. Whoever lost the money wasn't very responsible and should learn a lesson, added Mike. When Jay, Mike and Tony met back up after dinner, Mike and Tony conceded that Jay was right. They all rode their bikes to the police station together to turn in the money clip. The police officer who took the report told them that he was impressed with their honesty. He also said that if no one claimed the lost item, it would rightfully be theirs. The next morning, a man called the police station to report his lost money clip. When he found out it had been turned in, he was thrilled. The police officer handed Jay a gift certificate from the local bicycle shop for one hundred dollars."},
    {"id": 52, "level": 3, "title": "What Police and Detectives Do", "content": "Police officers protect lives and property. Detectives and criminal investigators gather facts and collect evidence of possible crimes. Uniformed police officers typically enforce laws, respond to emergency and nonemergency calls, patrol assigned areas, conduct traffic stops and issue citations, obtain warrants and arrest suspects, write detailed reports and fill out forms, and prepare cases and testify in court. Detectives and criminal investigators typically investigate crimes, collect and secure evidence from crime scenes, conduct interviews with suspects and witnesses, observe the activities of suspects, obtain warrants and arrest suspects, write detailed reports and fill out forms, and prepare cases and testify in court. Police officers pursue and apprehend people who break the law. Most police officers patrol their jurisdictions and investigate suspicious activity. They also respond to calls, issue traffic tickets, and give first aid to accident victims. Detectives perform investigative duties, such as gathering facts and collecting evidence. The daily activities of police and detectives vary with their occupational specialty, such as canine units and special weapons and tactics."},
    {"id": 53, "level": 3, "title": "Space Based Astronomy",   "content": "If you go to the country, far from city lights, you can see about 3,000 stars on a clear night. If your eyes were bigger, you could see many more stars. With a pair of binoculars, the number of stars you can see increases to the tens of thousands. With a large observatory telescope, millions of stars become visible. Surrounding Earth is a life-sustaining atmosphere that stands between our eyes and the radiation that falls upon Earth from outer space. This radiation is comprised of a very broad spectrum of energies and wavelengths. Collectively, they are referred to as the electromagnetic spectrum. Gases and other components of our atmosphere distort, filter, and block most of this radiation permitting only a partial picture to reach Earth's surface. Although many things can be learned about our universe by studying it from the surface of Earth, the story is incomplete. To view celestial objects over the whole range of the electromagnetic spectrum, it is essential to climb above the atmosphere into outer space. From its earliest days, NASA has used the emerging technology of rockets to explore the universe. By lofting telescopes above the veil of Earth's atmosphere, NASA has delivered a treasure house of information to astronomers."},
    {"id": 54, "level": 3, "title": "Curious About Careers: Mechanical Engineering", "content": "Do you like to build with blocks? Are you curious about how solar panels turn sun rays into electricity? Have you wondered how planes stay in the air? Do you wonder why putting gas into cars causes the wheels to turn? Do you like to design and create new things? If you do, a career in mechanical engineering might be right for you! A mechanical engineer is responsible for coming up with and designing mechanical systems. Mechanical systems can include machine design, heating and cooling equipment, power generation, and product design. Products like the latest cellphone begin with an engineer coming up with the idea. Mechanical engineers are in high demand right now. That means that there are a lot of job openings for mechanical engineers, but there aren't enough people to fill those jobs. To be a mechanical engineer, you need to graduate from college with a bachelor's degree. Problem solving is very important in the field of mechanical engineering. People in this career need to be able to think about problems in different ways to figure out the best solution. Mechanical engineering takes a lot of thought. It is a great career for people who like to make objects and machines work, solve problems, and be creative!"},
    {"id": 55, "level": 3, "title": "Curious About Careers: Teacher", "content": "Do you enjoy working with kids? Do you like helping people? Is learning fun for you? Teaching could be the career for you! Teachers need to graduate from college and get their teaching license. This requires taking some tests and working with another teacher for a few months. Teachers need to be able to work well with other people. They need to work with students, parents, other teachers, and other staff members at the school. As most kids know, teachers also have to do a lot of grading. They grade math tests, spelling tests, and many other papers. Most teachers are told what information they have to teach, but they may get to choose how to teach it. Teachers may use technology, art, books, and experiments to teach their topics. Teachers have to continue to learn throughout their careers. They attend workshops, take classes, read books, and research teaching topics online. Not only do teachers have to get along with many different types of people, plan lessons, and keep learning, but they also have to keep track of how students are doing. There is a lot of work to do as a teacher, both during school and after school, but working with students is a lot of fun, too!"},
    {"id": 56, "level": 3, "title": "Horses",                  "content": "Horses are beautiful creatures. They can be different colors, and can run quickly. People like to watch horses because they are strong and powerful. Horses are mammals. Mammals are animals that have hair or fur, are warm-blooded, and usually give birth to live young. The mother horse generally has one baby in the spring, and feeds the baby milk. Horses have long legs, and big eyes that can see almost all the way around them. They can walk, trot, gallop and jump. Young horses that are one year old or younger are called foals. A young female horse is called a filly, and a young male horse is called a colt. After 4 years, a horse is considered an adult. Many people think that a pony is a young horse, but that is incorrect. A pony is a type of horse that does not grow very large. Horses can live up to 20 or 25 years. Sometimes people can tell how old a horse is by looking at its teeth! They generally sleep standing up, so that if a predator approaches, they can run away quickly. Horses only need about three hours of sleep per day!"},
    {"id": 57, "level": 3, "title": "How to Care for a Pet Fish","content": "Taking care of a pet is a big responsibility, so you want to make sure you learn all about your pet before bringing it home! Many kids have fish as their first pet. First, choose what types of fish and how many fish you will be getting. Freshwater fish are the best fish to start with, until you get really good at taking care of fish and their tanks. Some types of fish do not get along with other types, so you'll need to research types of fish before you choose what types and how many to buy. Next, you need to make sure you have all of the necessary supplies that your fish will need. They need a place to live, such as a fish tank with a lid on it. Fish tanks also need a light, so that they can tell the difference between night and day, and an air pump and filter, to keep the water from getting dirty too quickly. The water needs to be kept at a comfortable temperature for your type of fish. Now that you have your supplies, you'll need to set up your aquarium. Put the tank on the stand, close enough to an outlet so that you can plug in the equipment. You are ready to pick up your fish! Feed them in small amounts a few times a day. Too much extra food will make the quality of the water bad. You will have to change some of the water at least once a week. Enjoy your new pets!"},
    {"id": 58, "level": 3, "title": "The Goose Voyage",        "content": "Are you ready Greg? Shane asked. It's going to be one long adventure! I was born ready! I answered. We were all getting ready for our yearly migration south. The days were growing shorter, the weather was getting colder, and we all just felt like it was time to move. This was mine and Shane's first time migrating. We were a little nervous about going, but everyone in the flock reassured us that we'd know exactly what to do. Well, let's go! Shane said. We met up with the rest of the flock. Shane's mom was going to be the point of the flock first. We were all going to fly in a V shape, because they all said it makes it easier on everyone else to fly behind the point. Higher and higher we flew, then everyone started leveling off. Flying always felt great, it was fun to look at everything far below us. I went to find Shane as soon as we landed. I'm glad we have a break, we need it. I'm shaken up! he answered. Shaken up? Why? It's been pretty boring so far! I said. Didn't you see the eagle? It was coming after us! It almost got Lucy! Shane exclaimed. Hopefully that will be the only crazy thing that happens during this migration. Let's get some rest. We have another busy day of flying tomorrow."},
    {"id": 59, "level": 3, "title": "Friends Over Fears",      "content": "For as long as Mia could remember, she had been terrified of snakes. She had skipped the class field trip to the zoo, and on the day James had brought his pet snake into their seventh-grade math class, Mia had run into the hallway, tears pooling in her eyes. With every passing year, Mia's fear of snakes seemed to be getting worse. Jess had been Mia's best friend since kindergarten. Jess wasn't afraid of snakes or anything else that crawled or slithered. Jess knew all about Mia's snake phobia, and she used to find it funny, but now it had grown worrisome. As Mia stepped into Jess' room, she froze. What's that? Over Jess's shoulder, she could see a massive glass tank. Suddenly, a scaly tail flashed out from beneath some leaves. Mia jumped and let out a shriek. Tiger is totally contained in the tank, Mia. She can't escape, Jess offered. Mia decided to be brave. I'm going to try, but don't let me go anywhere near Tiger. The girls played the video game every day after school that week. Mia was still bothered by the snake, but at least her stomach wasn't churning anymore when she thought about it. Would you like to hold her? Jess inquired. Mia watched, petrified, as Jess lowered Tiger into her arms. When I first told you about my fear of snakes, I did everything I could to keep them away from you. But when you started to avoid the park, I realized I needed to help you conquer your fears. So I started researching snakes, and I searched for the smallest, most harmless one that I could bring home. When I finally chose Tiger, the purchase wasn't for me. It was for you."},
    {"id": 60, "level": 3, "title": "Babushka and the Nomads", "content": "Dahlia couldn't believe that she was missing Sarah's birthday party for this. Instead, she was stranded for the summer in Kyrgyzstan with only her babushka, Aidana, for company. Dahlia stared forlornly out of the window of Aidana's car, watching the Kyrgyzstan countryside roll by. Stop pouting, Aidana scolded. I know that you don't want to be here, but it is important that you know about where you come from and learn about our culture. Pulling out her phone, Dahlia opened the YouTube app. When the home page failed to load, her eyes flicked to the bars at the top of her screen. Zero reception. Derek Yeon was Dahlia's favorite YouTuber. The 23-year-old aspiring journalist travelled the world documenting the lives of everyday people. A short time later, they came upon a village constructed of portable round tents known as yurts. This is the World Nomad Games. Think of it like the Olympics of Asia. Standing directly behind her in all his glory was Derek Yeon, a video camera around his neck. You're Derek Yeon. Derek smiled. I take it you're familiar with my work. I could be your translator, if you like. Dahlia had long forgotten about her friend's birthday party. She marveled at the countryside on the drive home and looked forward to meeting more Kyrgyz and learning more about their culture."},
]

# ════════════════════════════════
#        QUESTIONS DATA
# ════════════════════════════════

questions = [
    # Story 1
    {"passage_id": 1, "question_text": "How did Kitten feel after chasing the mouse?", "option_1": "Angry at her brother", "option_2": "Happy with her choice", "option_3": "Tired and bored", "correct_answer": "Option_2"},
    {"passage_id": 1, "question_text": "What would happen if Kitten chose the toy instead of the mouse?", "option_1": "The mouse would run away", "option_2": "The toy would disappear", "option_3": "Her brother would take the toy", "correct_answer": "Option_1"},
    {"passage_id": 1, "question_text": "What animal did Kitten see?", "option_1": "Bird", "option_2": "Mouse", "option_3": "Fish", "correct_answer": "Option_2"},
    # Story 2
    {"passage_id": 2, "question_text": "Who got the cookie?", "option_1": "Jan", "option_2": "Sam", "option_3": "Tim", "correct_answer": "Option_3"},
    {"passage_id": 2, "question_text": "What dessert did Ben get?", "option_1": "Cake", "option_2": "Donut", "option_3": "Cookie", "correct_answer": "Option_2"},
    {"passage_id": 2, "question_text": "Why was Sam happy at the end?", "option_1": "He got his own dessert", "option_2": "He ate pie only", "option_3": "His friends shared their desserts with him", "correct_answer": "Option_3"},
    # Story 3
    {"passage_id": 3, "question_text": "What is Bear getting ready for?", "option_1": "Summer", "option_2": "Winter", "option_3": "Fall", "correct_answer": "Option_2"},
    {"passage_id": 3, "question_text": "What does Bear fill his den with to stay warm?", "option_1": "Sticks", "option_2": "Leaves", "option_3": "Rocks", "correct_answer": "Option_2"},
    {"passage_id": 3, "question_text": "What is the first thing Bear does to get ready for winter?", "option_1": "Eats a lot", "option_2": "Sleeps", "option_3": "Finds a den", "correct_answer": "Option_1"},
    # Story 4
    {"passage_id": 4, "question_text": "Which animal did the speaker see first?", "option_1": "Black bear", "option_2": "White bear", "option_3": "Camel", "correct_answer": "Option_2"},
    {"passage_id": 4, "question_text": "What was the grey wolf carrying in its mouth?", "option_1": "Fish", "option_2": "Mutton", "option_3": "Straw", "correct_answer": "Option_2"},
    {"passage_id": 4, "question_text": "Which animal had a hump on its back?", "option_1": "Camel", "option_2": "Wombat", "option_3": "Monkey", "correct_answer": "Option_1"},
    # Story 5
    {"passage_id": 5, "question_text": "What did Jake ask his mom to make for breakfast?", "option_1": "Toast", "option_2": "Waffles", "option_3": "Oatmeal", "correct_answer": "Option_2"},
    {"passage_id": 5, "question_text": "What did Jake's cat become?", "option_1": "A magic carpet", "option_2": "A king", "option_3": "A sea monster", "correct_answer": "Option_3"},
    {"passage_id": 5, "question_text": "What did Jake eat in his tent?", "option_1": "Hot dogs", "option_2": "Chocolate covered ants", "option_3": "Bacon and eggs", "correct_answer": "Option_1"},
    # Story 6
    {"passage_id": 6, "question_text": "What color is Emma's new bicycle?", "option_1": "Red", "option_2": "Blue", "option_3": "Pink", "correct_answer": "Option_3"},
    {"passage_id": 6, "question_text": "Who gave Emma the bicycle?", "option_1": "Her friend", "option_2": "Her uncle", "option_3": "Her mother", "correct_answer": "Option_2"},
    {"passage_id": 6, "question_text": "Where did Emma's uncle hide the bicycle?", "option_1": "In the park", "option_2": "Behind a bush", "option_3": "In her room", "correct_answer": "Option_2"},
    # Story 7
    {"passage_id": 7, "question_text": "What did Penny want more than anything as a pet?", "option_1": "A puppy", "option_2": "A kitten", "option_3": "A pony", "correct_answer": "Option_3"},
    {"passage_id": 7, "question_text": "Where did Penny suggest a pony could sleep?", "option_1": "In Penny's bed", "option_2": "In the doghouse", "option_3": "On the couch", "correct_answer": "Option_1"},
    {"passage_id": 7, "question_text": "Why did Penny's mom not think the pony could spend time on the balcony?", "option_1": "The pony might jump over the railing", "option_2": "The pony might be afraid of heights", "option_3": "The pony might fall", "correct_answer": "Option_2"},
    # Story 8
    {"passage_id": 8, "question_text": "What kind of puzzles is Anna best at?", "option_1": "Big puzzles", "option_2": "Little puzzles", "option_3": "Car puzzles", "correct_answer": "Option_2"},
    {"passage_id": 8, "question_text": "How many pieces did the family's big puzzle last year have?", "option_1": "100", "option_2": "250", "option_3": "500", "correct_answer": "Option_3"},
    {"passage_id": 8, "question_text": "What do Anna and her family do with their favorite puzzles?", "option_1": "Give them to friends", "option_2": "Sell them", "option_3": "Glue and frame them", "correct_answer": "Option_3"},
    # Story 9
    {"passage_id": 9, "question_text": "What were the kids doing before the storm?", "option_1": "Playing catch", "option_2": "Watching TV", "option_3": "Riding bikes", "correct_answer": "Option_1"},
    {"passage_id": 9, "question_text": "Why did the kids go inside?", "option_1": "They wanted to see a rainbow", "option_2": "A storm was coming", "option_3": "They were tired", "correct_answer": "Option_2"},
    {"passage_id": 9, "question_text": "What did the kids see after the storm?", "option_1": "A kite", "option_2": "A rainbow", "option_3": "Sunshine", "correct_answer": "Option_2"},
    # Story 10
    {"passage_id": 10, "question_text": "When did they go to the new water park?", "option_1": "On the first day of summer", "option_2": "On a rainy day", "option_3": "On the last day of summer", "correct_answer": "Option_1"},
    {"passage_id": 10, "question_text": "What is not allowed at the water park?", "option_1": "Donuts", "option_2": "Ice cream", "option_3": "Pets", "correct_answer": "Option_3"},
    {"passage_id": 10, "question_text": "What snack do they like the most at the snack bar?", "option_1": "Ice cream", "option_2": "Candy", "option_3": "Pop", "correct_answer": "Option_1"},
    # Story 11
    {"passage_id": 11, "question_text": "What kind of cookies does Greg like the most?", "option_1": "Oatmeal cookies", "option_2": "Chocolate chip cookies", "option_3": "Sugar cookies", "correct_answer": "Option_2"},
    {"passage_id": 11, "question_text": "What does Greg do while the cookies are baking?", "option_1": "Washes the dishes", "option_2": "Licks the last bits of batter from the bowl", "option_3": "Reads a book", "correct_answer": "Option_2"},
    {"passage_id": 11, "question_text": "How long does it take for the cookies to bake?", "option_1": "30 minutes", "option_2": "20 minutes", "option_3": "35 minutes", "correct_answer": "Option_1"},
    # Story 12
    {"passage_id": 12, "question_text": "What was the mule trying to do?", "option_1": "Write a letter to his father", "option_2": "Milk a cow", "option_3": "Look for food", "correct_answer": "Option_1"},
    {"passage_id": 12, "question_text": "Why couldn't the mule finish the letter?", "option_1": "He didn't know what to say", "option_2": "He couldn't find the ink", "option_3": "He got too tired", "correct_answer": "Option_2"},
    {"passage_id": 12, "question_text": "What did the mule decide about writing letters home?", "option_1": "It was very important", "option_2": "It was fun", "option_3": "It was too much bother", "correct_answer": "Option_3"},
    # Story 13
    {"passage_id": 13, "question_text": "What was the problem with the monster?", "option_1": "He didn't know any of the classroom rules", "option_2": "He was too loud in the classroom", "option_3": "He didn't like to play games", "correct_answer": "Option_1"},
    {"passage_id": 13, "question_text": "What did the monster try to do in the gym?", "option_1": "Throw a ball without learning", "option_2": "Run loudly around the gym", "option_3": "Sit on the carpet and use a quiet voice", "correct_answer": "Option_3"},
    {"passage_id": 13, "question_text": "What did the students teach the monster in P.E. class?", "option_1": "How to be quiet in the gym", "option_2": "How to throw a ball", "option_3": "How to sit on the carpet", "correct_answer": "Option_2"},
    # Story 14
    {"passage_id": 14, "question_text": "What are baby bears called?", "option_1": "Cubs", "option_2": "Pups", "option_3": "Calves", "correct_answer": "Option_1"},
    {"passage_id": 14, "question_text": "Where do polar bears live?", "option_1": "Warm places", "option_2": "Cold places", "option_3": "Forests", "correct_answer": "Option_2"},
    {"passage_id": 14, "question_text": "What is it called when bears sleep all winter?", "option_1": "Resting", "option_2": "Hibernating", "option_3": "Snoring", "correct_answer": "Option_2"},
    # Story 15
    {"passage_id": 15, "question_text": "Where did the family get the puppy and kitten?", "option_1": "From a pet store", "option_2": "From the animal shelter", "option_3": "From a neighbor", "correct_answer": "Option_2"},
    {"passage_id": 15, "question_text": "What name did the family choose for the puppy?", "option_1": "Cuddles", "option_2": "Jump", "option_3": "Pounce", "correct_answer": "Option_3"},
    {"passage_id": 15, "question_text": "What does the kitten like to do?", "option_1": "Curl up in laps", "option_2": "Chase balls", "option_3": "Jump on furniture", "correct_answer": "Option_1"},
    # Story 16
    {"passage_id": 16, "question_text": "What is happening along the lakeshore?", "option_1": "A fishing contest", "option_2": "A summer boat parade", "option_3": "A swimming race", "correct_answer": "Option_2"},
    {"passage_id": 16, "question_text": "Which boat is Jessica's favorite?", "option_1": "The yellow motorboat with the flag", "option_2": "The rowboat decorated with flowers", "option_3": "The purple sailboat", "correct_answer": "Option_1"},
    {"passage_id": 16, "question_text": "What is Lisa's favorite boat?", "option_1": "The purple sailboat", "option_2": "The yellow motorboat with the flag", "option_3": "The rowboat decorated with flowers", "correct_answer": "Option_3"},
    # Story 17
    {"passage_id": 17, "question_text": "Who is John going to the baseball game with?", "option_1": "His mom", "option_2": "His aunt", "option_3": "His friend", "correct_answer": "Option_2"},
    {"passage_id": 17, "question_text": "What are John's favorite snacks at the baseball game?", "option_1": "Peanuts and popcorn", "option_2": "Hot dogs and popcorn", "option_3": "Popcorn and candy", "correct_answer": "Option_1"},
    {"passage_id": 17, "question_text": "What does John do if he is really hungry?", "option_1": "Eats candy", "option_2": "Has a hot dog", "option_3": "Gets more popcorn", "correct_answer": "Option_2"},
    # Story 18
    {"passage_id": 18, "question_text": "How does the narrator earn money for the new toy?", "option_1": "By selling toys", "option_2": "By shoveling driveways", "option_3": "By delivering newspapers", "correct_answer": "Option_2"},
    {"passage_id": 18, "question_text": "Who is the first neighbor the narrator helps?", "option_1": "Mr. Tom", "option_2": "Mrs. Jen", "option_3": "Mom", "correct_answer": "Option_2"},
    {"passage_id": 18, "question_text": "What happens after the narrator shovels Mr. Tom's driveway?", "option_1": "He can get the new toy", "option_2": "He still needs more money", "option_3": "He buys candy", "correct_answer": "Option_1"},
    # Story 19
    {"passage_id": 19, "question_text": "What kind of video games does Brad like best?", "option_1": "Racing games", "option_2": "Sports games", "option_3": "Disney games", "correct_answer": "Option_3"},
    {"passage_id": 19, "question_text": "Why did Brad decide not to lie about his homework?", "option_1": "His mom was watching him closely", "option_2": "He didn't want to get a bad grade", "option_3": "He would lose his games for a week if he lied", "correct_answer": "Option_3"},
    {"passage_id": 19, "question_text": "What did Brad do before playing video games?", "option_1": "Ate dinner", "option_2": "Finished his homework", "option_3": "Helped his mom", "correct_answer": "Option_2"},
    # Story 20
    {"passage_id": 20, "question_text": "When do apples finish growing?", "option_1": "In the summer", "option_2": "In the fall", "option_3": "In the winter", "correct_answer": "Option_2"},
    {"passage_id": 20, "question_text": "What is the outside part of an apple called?", "option_1": "Skin", "option_2": "Flesh", "option_3": "Stem", "correct_answer": "Option_1"},
    {"passage_id": 20, "question_text": "What should you do to pick an apple from a tree?", "option_1": "Pull it straight down", "option_2": "Twist it and then pull it off", "option_3": "Shake the tree", "correct_answer": "Option_2"},
    # Story 21
    {"passage_id": 21, "question_text": "What gave the baker's cookies the snap to jump off the pan?", "option_1": "Eggs", "option_2": "Flour", "option_3": "Spice", "correct_answer": "Option_3"},
    {"passage_id": 21, "question_text": "What happened when the baker locked the bakery doors?", "option_1": "The cookies stayed in the pan", "option_2": "The cookies burned", "option_3": "The cookies ran wild inside the bakery", "correct_answer": "Option_3"},
    {"passage_id": 21, "question_text": "What did Chef Shiraz believe licorice would do in a hot oven?", "option_1": "He believed the licorice would stretch", "option_2": "He believed the licorice would melt", "option_3": "He believed the licorice would become hard", "correct_answer": "Option_2"},
    # Story 22
    {"passage_id": 22, "question_text": "What did Zander use to help his plants grow?", "option_1": "A watering can", "option_2": "A laser", "option_3": "A flashlight", "correct_answer": "Option_2"},
    {"passage_id": 22, "question_text": "What did Jules bring to Zander's house?", "option_1": "Some fruit", "option_2": "Lunch plants", "option_3": "Cleaning products", "correct_answer": "Option_3"},
    {"passage_id": 22, "question_text": "Why did Zander and Jules think trading was sometimes hard?", "option_1": "Sometimes they didn't have enough items ready", "option_2": "They didn't like each other", "option_3": "They lived too far away", "correct_answer": "Option_1"},
    # Story 23
    {"passage_id": 23, "question_text": "What were Johnny and his friends building?", "option_1": "A cardboard town", "option_2": "A toy car", "option_3": "A treehouse", "correct_answer": "Option_1"},
    {"passage_id": 23, "question_text": "Why did Johnny decide to say sorry to Katie and Max?", "option_1": "He wanted them to bring more boxes", "option_2": "He realized building was faster and more fun when they worked together", "option_3": "He needed someone to show the town to", "correct_answer": "Option_2"},
    {"passage_id": 23, "question_text": "What happened after Johnny and his friends worked together again?", "option_1": "The town was finished quickly", "option_2": "They stopped talking to each other", "option_3": "They decided to build something else", "correct_answer": "Option_1"},
    # Story 24
    {"passage_id": 24, "question_text": "What do Kate and Jake play catch with?", "option_1": "Frisbees", "option_2": "Beanbags", "option_3": "Balls", "correct_answer": "Option_3"},
    {"passage_id": 24, "question_text": "What type do they use to play catch on rainy days?", "option_1": "Pillows", "option_2": "Tennis balls", "option_3": "Soccer balls", "correct_answer": "Option_2"},
    {"passage_id": 24, "question_text": "Where do Kate and Jake go the week before he leaves for camp?", "option_1": "The park", "option_2": "The school", "option_3": "The beach", "correct_answer": "Option_1"},
    # Story 25
    {"passage_id": 25, "question_text": "What did Mom say Sly would do while Erin slept?", "option_1": "Watch over her through the night", "option_2": "Go outside to play", "option_3": "Catch a mouse", "correct_answer": "Option_1"},
    {"passage_id": 25, "question_text": "What happened when Sly tried to get the cat treats?", "option_1": "He found the treats and ate them", "option_2": "He knocked over a bowl of water", "option_3": "He knocked down a bag of pepper", "correct_answer": "Option_3"},
    {"passage_id": 25, "question_text": "What did Sly do after the mouse escaped?", "option_1": "Kept trying to catch it", "option_2": "Went back upstairs to Erin", "option_3": "Hid under the bed", "correct_answer": "Option_2"},
    # Story 26
    {"passage_id": 26, "question_text": "What do students need before they can go to the movies?", "option_1": "Movie tickets", "option_2": "Permission slips signed", "option_3": "A snack", "correct_answer": "Option_2"},
    {"passage_id": 26, "question_text": "What is the movie about?", "option_1": "A story from a book they read", "option_2": "A true story about their school", "option_3": "A story about popcorn", "correct_answer": "Option_1"},
    {"passage_id": 26, "question_text": "Why did the class like the book better than the movie?", "option_1": "Books have more pictures", "option_2": "Books let you picture the characters any way you want", "option_3": "The book was shorter", "correct_answer": "Option_2"},
    # Story 27
    {"passage_id": 27, "question_text": "What color is Dave's kayak?", "option_1": "Red", "option_2": "Yellow", "option_3": "Blue", "correct_answer": "Option_2"},
    {"passage_id": 27, "question_text": "What do Dave and Grant sometimes bring with them when kayaking?", "option_1": "Fishing poles", "option_2": "Cameras", "option_3": "Binoculars", "correct_answer": "Option_1"},
    {"passage_id": 27, "question_text": "What is their favorite spot on the lake used for?", "option_1": "Taking pictures of ducks", "option_2": "Racing their kayaks", "option_3": "Eating their sandwiches", "correct_answer": "Option_3"},
    # Story 28
    {"passage_id": 28, "question_text": "What did Tyler's mom tell him to do if he wanted to ride his bike to the park?", "option_1": "Bring a garbage bag", "option_2": "Wear gloves", "option_3": "Wear his helmet", "correct_answer": "Option_3"},
    {"passage_id": 28, "question_text": "What were people doing in the park when Tyler arrived?", "option_1": "Playing soccer", "option_2": "Cleaning up garbage", "option_3": "Having a picnic", "correct_answer": "Option_2"},
    {"passage_id": 28, "question_text": "What did the teachers give everyone after cleaning the park?", "option_1": "Ice cream and soda", "option_2": "Pizza and lemonade", "option_3": "Sandwiches and juice", "correct_answer": "Option_2"},
    # Story 29
    {"passage_id": 29, "question_text": "What surprise did Mia's dad give her one frosty morning?", "option_1": "A trip to the zoo", "option_2": "A new coat", "option_3": "A pet polar bear", "correct_answer": "Option_1"},
    {"passage_id": 29, "question_text": "How did the lion stay warm at the zoo in the winter?", "option_1": "A heating pad hidden inside the fake rocks", "option_2": "A big blanket", "option_3": "A heat lamp above him", "correct_answer": "Option_1"},
    {"passage_id": 29, "question_text": "Why did the giraffes go inside during the winter?", "option_1": "They don't like the snow", "option_2": "They prefer to sleep inside", "option_3": "They might slip on ice with their long legs and necks", "correct_answer": "Option_3"},
    # Story 30
    {"passage_id": 30, "question_text": "What should you do if you try and do not win?", "option_1": "Stop trying", "option_2": "Cry and give up", "option_3": "Keep trying patiently", "correct_answer": "Option_3"},
    {"passage_id": 30, "question_text": "What happens to young birds when they practice flying?", "option_1": "They get weaker", "option_2": "They fall but their wings grow stronger", "option_3": "They never fall", "correct_answer": "Option_2"},
    {"passage_id": 30, "question_text": "What does the poem say is the real test?", "option_1": "Winning the first time you try", "option_2": "Gaining victory after being defeated", "option_3": "Avoiding hard work", "correct_answer": "Option_2"},
    # Story 31
    {"passage_id": 31, "question_text": "Who went camping with Lily and Ryan?", "option_1": "Their friends", "option_2": "Their mom and dad", "option_3": "Their teacher", "correct_answer": "Option_2"},
    {"passage_id": 31, "question_text": "How many hot dogs did each person cook?", "option_1": "One", "option_2": "Two", "option_3": "Three", "correct_answer": "Option_2"},
    {"passage_id": 31, "question_text": "What did they roast for dessert?", "option_1": "Marshmallows", "option_2": "Apples", "option_3": "Bread", "correct_answer": "Option_1"},
    # Story 32
    {"passage_id": 32, "question_text": "Why did Shari's mom ask her to give away some toys?", "option_1": "To make space for new toys", "option_2": "Because Shari didn't like toys anymore", "option_3": "To sell them at a store", "correct_answer": "Option_1"},
    {"passage_id": 32, "question_text": "Where did Shari and her mom take the toys?", "option_1": "To a friend's house", "option_2": "To a place where kids without homes lived", "option_3": "To a toy store", "correct_answer": "Option_2"},
    {"passage_id": 32, "question_text": "How did Shari feel after giving away the toys?", "option_1": "Sad", "option_2": "Angry", "option_3": "Happy", "correct_answer": "Option_3"},
    # Story 33
    {"passage_id": 33, "question_text": "What kind of music does Jake play?", "option_1": "Jazz and pop", "option_2": "Classical and blues", "option_3": "Country and rock and roll", "correct_answer": "Option_3"},
    {"passage_id": 33, "question_text": "Why is Emma not sure if she can take guitar lessons?", "option_1": "She doesn't like music", "option_2": "She has too many other activities", "option_3": "Her mom said no", "correct_answer": "Option_2"},
    {"passage_id": 33, "question_text": "What does Emma decide at the end?", "option_1": "To quit ballet", "option_2": "To take guitar lessons", "option_3": "To keep enjoying her brother's guitar playing", "correct_answer": "Option_3"},
    # Story 34
    {"passage_id": 34, "question_text": "Where does Emma's pen pal Oliver live?", "option_1": "France", "option_2": "England", "option_3": "Canada", "correct_answer": "Option_2"},
    {"passage_id": 34, "question_text": "What holiday does Oliver celebrate that the narrator doesn't?", "option_1": "April Fool's Day", "option_2": "Boxing Day", "option_3": "Halloween", "correct_answer": "Option_2"},
    {"passage_id": 34, "question_text": "What was one of the required questions to include in the letter?", "option_1": "What is your favorite food?", "option_2": "Which holidays do you celebrate?", "option_3": "How old are you?", "correct_answer": "Option_2"},
    # Story 35
    {"passage_id": 35, "question_text": "What were Molly and Bella supposed to be doing at the playground?", "option_1": "Playing tag", "option_2": "Taking turns on the swing", "option_3": "Playing on the slide", "correct_answer": "Option_2"},
    {"passage_id": 35, "question_text": "What is an I message?", "option_1": "A text message", "option_2": "Telling someone how you feel and what you need", "option_3": "A letter to a teacher", "correct_answer": "Option_2"},
    {"passage_id": 35, "question_text": "How did Molly feel after solving the problem?", "option_1": "Angry", "option_2": "Sad", "option_3": "Happy", "correct_answer": "Option_3"},
    # Story 36
    {"passage_id": 36, "question_text": "What do Max and Will love to catch at the pond?", "option_1": "Fish", "option_2": "Tadpoles", "option_3": "Turtles", "correct_answer": "Option_2"},
    {"passage_id": 36, "question_text": "Why do they keep the tub in the shade?", "option_1": "So the tadpoles can sleep", "option_2": "So the water does not get too hot", "option_3": "So animals can't find them", "correct_answer": "Option_2"},
    {"passage_id": 36, "question_text": "How long does it take for the tadpoles to grow into frogs?", "option_1": "Two weeks", "option_2": "One month", "option_3": "Six weeks", "correct_answer": "Option_3"},
    # Story 37
    {"passage_id": 37, "question_text": "Where does Ella's grandpa live?", "option_1": "Florida", "option_2": "Texas", "option_3": "California", "correct_answer": "Option_2"},
    {"passage_id": 37, "question_text": "What is Ella's favorite dinner?", "option_1": "Pizza", "option_2": "Spaghetti", "option_3": "Barbeque chicken", "correct_answer": "Option_3"},
    {"passage_id": 37, "question_text": "What does Grandpa do the next time he visits?", "option_1": "Buys Ella a present", "option_2": "Teaches Ella and her mom how to make the chicken", "option_3": "Makes the chicken himself", "correct_answer": "Option_2"},
    # Story 38
    {"passage_id": 38, "question_text": "Why couldn't Red Race car sleep?", "option_1": "He was too excited", "option_2": "He was feeling nervous for the race", "option_3": "The garage was too loud", "correct_answer": "Option_2"},
    {"passage_id": 38, "question_text": "What technique did Blue Race car suggest to feel better?", "option_1": "Counting sheep", "option_2": "Taking deep breaths", "option_3": "Listening to music", "correct_answer": "Option_2"},
    {"passage_id": 38, "question_text": "How did the race cars feel after the deep breathing?", "option_1": "More nervous", "option_2": "Hungry", "option_3": "Calm", "correct_answer": "Option_3"},
    # Story 39
    {"passage_id": 39, "question_text": "Why did Sarah's family need a new washing machine?", "option_1": "They wanted a bigger one", "option_2": "The old one stopped working", "option_3": "They moved to a new house", "correct_answer": "Option_2"},
    {"passage_id": 39, "question_text": "What did Sarah and Emily turn the box into first?", "option_1": "A car", "option_2": "A TV", "option_3": "A clubhouse", "correct_answer": "Option_3"},
    {"passage_id": 39, "question_text": "What did Sarah and Emily do with the box at the end?", "option_1": "They threw it away", "option_2": "They cut out a square and made it into a TV", "option_3": "They painted it blue", "correct_answer": "Option_2"},
    # Story 40
    {"passage_id": 40, "question_text": "What are baby sharks called?", "option_1": "Cubs", "option_2": "Pups", "option_3": "Kittens", "correct_answer": "Option_2"},
    {"passage_id": 40, "question_text": "How many types of sharks are there?", "option_1": "Over 100", "option_2": "Over 200", "option_3": "Over 400", "correct_answer": "Option_3"},
    {"passage_id": 40, "question_text": "What do most sharks eat?", "option_1": "Plants", "option_2": "Other animals", "option_3": "Seaweed", "correct_answer": "Option_2"},
    # Story 41
    {"passage_id": 41, "question_text": "What problem did Vicky find in her basement?", "option_1": "A broken pipe", "option_2": "Flooding water", "option_3": "A power outage", "correct_answer": "Option_2"},
    {"passage_id": 41, "question_text": "What did Vicky's family do to help their neighbors?", "option_1": "Cooked food for them", "option_2": "Filled sandbags to keep water away", "option_3": "Gave them money", "correct_answer": "Option_2"},
    {"passage_id": 41, "question_text": "What did Vicky's dad suggest they should do?", "option_1": "Move to another town", "option_2": "Go through their stuff and donate", "option_3": "Buy a new house", "correct_answer": "Option_2"},
    # Story 42
    {"passage_id": 42, "question_text": "What was the parents' rule about concerts?", "option_1": "You must be in fifth grade", "option_2": "You must be in sixth grade", "option_3": "You must be 13 years old", "correct_answer": "Option_2"},
    {"passage_id": 42, "question_text": "What was one of the conditions the parents set?", "option_1": "Get an A on their next book report", "option_2": "Clean their rooms every day", "option_3": "Cook dinner for a week", "correct_answer": "Option_1"},
    {"passage_id": 42, "question_text": "Who took Alex and Amanda to the concert?", "option_1": "Their mom", "option_2": "Their dad", "option_3": "Their older sister Andrea", "correct_answer": "Option_3"},
    # Story 43
    {"passage_id": 43, "question_text": "What did Mrs. Lindsey give each student to make their constellation?", "option_1": "A poster board and glow-in-the-dark marker", "option_2": "A telescope and star chart", "option_3": "A notebook and pencil", "correct_answer": "Option_1"},
    {"passage_id": 43, "question_text": "What is Ursa Minor also called?", "option_1": "The Big Dipper", "option_2": "The Little Dipper", "option_3": "The North Star", "correct_answer": "Option_2"},
    {"passage_id": 43, "question_text": "What did the students do after putting on their constellations?", "option_1": "They drew pictures of the sky", "option_2": "They circled the classroom like dancing stars", "option_3": "They went outside to look at the real stars", "correct_answer": "Option_2"},
    # Story 44
    {"passage_id": 44, "question_text": "What did Alexa do that she should have done right away?", "option_1": "Returned Brittany's notebook", "option_2": "Apologized for being mean", "option_3": "Told Mrs. Stone she had Brittany's notebook", "correct_answer": "Option_3"},
    {"passage_id": 44, "question_text": "What solution did Mrs. Stone help the girls find?", "option_1": "To stop being friends", "option_2": "To play together a couple times a week and take turns picking the activity", "option_3": "To always play soccer together", "correct_answer": "Option_2"},
    {"passage_id": 44, "question_text": "What sport does Brittany prefer?", "option_1": "Ballet", "option_2": "Swimming", "option_3": "Soccer", "correct_answer": "Option_3"},
    # Story 45
    {"passage_id": 45, "question_text": "What pet did the narrator bring to school?", "option_1": "A cat", "option_2": "A dog named Jax", "option_3": "A parakeet", "correct_answer": "Option_2"},
    {"passage_id": 45, "question_text": "What unusual animals did the narrator see at school?", "option_1": "A lion and a tiger", "option_2": "A kangaroo and a peacock", "option_3": "A monkey and a giraffe", "correct_answer": "Option_2"},
    {"passage_id": 45, "question_text": "How did the story end?", "option_1": "The narrator woke up from a dream", "option_2": "The principal sent everyone home", "option_3": "All the pets escaped", "correct_answer": "Option_1"},
    # Story 46
    {"passage_id": 46, "question_text": "What meal did Matt complain about at the beginning?", "option_1": "Spaghetti", "option_2": "Meatloaf", "option_3": "Chicken", "correct_answer": "Option_2"},
    {"passage_id": 46, "question_text": "What did Matt learn from taking over dinner?", "option_1": "Cooking is easy and fun", "option_2": "It is hard to please everyone and cooking takes a lot of work", "option_3": "He wants to be a chef", "correct_answer": "Option_2"},
    {"passage_id": 46, "question_text": "What did Matt's sister Sophia not like?", "option_1": "Chicken", "option_2": "Rice", "option_3": "Corn", "correct_answer": "Option_3"},
    # Story 47
    {"passage_id": 47, "question_text": "What was happening to Jamie's drawings overnight?", "option_1": "They were being thrown away", "option_2": "They were disappearing", "option_3": "They were being copied", "correct_answer": "Option_2"},
    {"passage_id": 47, "question_text": "What did the video reveal was taking the drawings?", "option_1": "A thief", "option_2": "The wind", "option_3": "Fairies", "correct_answer": "Option_3"},
    {"passage_id": 47, "question_text": "What did Jamie and Tony do to communicate with the fairies?", "option_1": "Left them a gift", "option_2": "Left them a note", "option_3": "Shouted at midnight", "correct_answer": "Option_2"},
    # Story 48
    {"passage_id": 48, "question_text": "How many fingers did the mysterious fossil creature have on each hand?", "option_1": "5", "option_2": "6", "option_3": "7", "correct_answer": "Option_2"},
    {"passage_id": 48, "question_text": "What did the fossil look like the second morning?", "option_1": "A dinosaur", "option_2": "A human", "option_3": "A small bear", "correct_answer": "Option_3"},
    {"passage_id": 48, "question_text": "What did the scientists set up to watch the fossil at night?", "option_1": "Security cameras", "option_2": "A rotation of two people watching at all times", "option_3": "A glass case", "correct_answer": "Option_2"},
    # Story 49
    {"passage_id": 49, "question_text": "What race did the siblings have?", "option_1": "Who could run faster", "option_2": "Who could clean their room fastest", "option_3": "Who could eat breakfast first", "correct_answer": "Option_2"},
    {"passage_id": 49, "question_text": "What clue did Aiden find near the pie?", "option_1": "A cat's paw print", "option_2": "A bird footprint", "option_3": "A dog's fur", "correct_answer": "Option_2"},
    {"passage_id": 49, "question_text": "What did Mom suggest they do since the pie was ruined?", "option_1": "Make another pie", "option_2": "Go out for ice cream", "option_3": "Order pizza", "correct_answer": "Option_2"},
    # Story 50
    {"passage_id": 50, "question_text": "What did Scott want to do during winter break?", "option_1": "Go snowboarding", "option_2": "Stay home and play video games", "option_3": "Visit his grandparents", "correct_answer": "Option_1"},
    {"passage_id": 50, "question_text": "What activity on the ship did Scott enjoy the most?", "option_1": "Swimming", "option_2": "Surfing", "option_3": "Playing games", "correct_answer": "Option_2"},
    {"passage_id": 50, "question_text": "How did Scott feel about the vacation at the end?", "option_1": "He was still disappointed", "option_2": "He said it was his best vacation ever", "option_3": "He wanted to go home early", "correct_answer": "Option_2"},
    # Story 51
    {"passage_id": 51, "question_text": "What did Jay find on the ground?", "option_1": "A lost wallet", "option_2": "A gold money clip with five hundred dollars", "option_3": "A diamond ring", "correct_answer": "Option_2"},
    {"passage_id": 51, "question_text": "What did Jay decide to do with the money?", "option_1": "Split it with his friends", "option_2": "Keep it all for himself", "option_3": "Turn it in to the police", "correct_answer": "Option_3"},
    {"passage_id": 51, "question_text": "What reward did Jay receive?", "option_1": "A hundred dollars cash", "option_2": "A gift certificate from the local bicycle shop", "option_3": "A new dirt bike", "correct_answer": "Option_2"},
    # Story 52
    {"passage_id": 52, "question_text": "What do detectives do at crime scenes?", "option_1": "Arrest suspects immediately", "option_2": "Collect and secure evidence", "option_3": "Write traffic tickets", "correct_answer": "Option_2"},
    {"passage_id": 52, "question_text": "What are state police officers sometimes called?", "option_1": "Detectives", "option_2": "State troopers or highway patrol officers", "option_3": "Sheriffs", "correct_answer": "Option_2"},
    {"passage_id": 52, "question_text": "What tools do most police officers carry?", "option_1": "Cameras and notebooks", "option_2": "Radios, handcuffs, and guns", "option_3": "Computers and phones", "correct_answer": "Option_2"},
    # Story 53
    {"passage_id": 53, "question_text": "How many stars can you see on a clear night from the country?", "option_1": "About 1000", "option_2": "About 3000", "option_3": "About 5000", "correct_answer": "Option_2"},
    {"passage_id": 53, "question_text": "What does Earth's atmosphere do to radiation from space?", "option_1": "Lets all of it through", "option_2": "Distorts, filters, and blocks most of it", "option_3": "Reflects it back into space", "correct_answer": "Option_2"},
    {"passage_id": 53, "question_text": "What has NASA used to explore the universe?", "option_1": "Satellites and robots", "option_2": "The emerging technology of rockets", "option_3": "Space shuttles only", "correct_answer": "Option_2"},
    # Story 54
    {"passage_id": 54, "question_text": "What degree do you need to become a mechanical engineer?", "option_1": "An associate's degree", "option_2": "A master's degree", "option_3": "A bachelor's degree", "correct_answer": "Option_3"},
    {"passage_id": 54, "question_text": "What is very important in the field of mechanical engineering?", "option_1": "Memorizing formulas", "option_2": "Problem solving", "option_3": "Drawing skills", "correct_answer": "Option_2"},
    {"passage_id": 54, "question_text": "Why do mechanical engineers get paid more than some other careers?", "option_1": "Because they work longer hours", "option_2": "Because the work requires specialized knowledge and there is high demand", "option_3": "Because they travel a lot", "correct_answer": "Option_2"},
    # Story 55
    {"passage_id": 55, "question_text": "What must teachers get before they can teach?", "option_1": "A master's degree", "option_2": "A teaching license", "option_3": "Ten years of experience", "correct_answer": "Option_2"},
    {"passage_id": 55, "question_text": "How do teachers keep learning throughout their careers?", "option_1": "They go back to school full time", "option_2": "They attend workshops, take classes, and read books", "option_3": "They watch educational TV", "correct_answer": "Option_2"},
    {"passage_id": 55, "question_text": "What is teaching a great career for?", "option_1": "People who love money", "option_2": "People who love to help others and keep learning", "option_3": "People who don't like working with others", "correct_answer": "Option_2"},
    # Story 56
    {"passage_id": 56, "question_text": "What is a young female horse called?", "option_1": "A foal", "option_2": "A filly", "option_3": "A colt", "correct_answer": "Option_2"},
    {"passage_id": 56, "question_text": "How many hours of sleep do horses need per day?", "option_1": "About eight hours", "option_2": "About five hours", "option_3": "About three hours", "correct_answer": "Option_3"},
    {"passage_id": 56, "question_text": "Why do horses sleep standing up?", "option_1": "Because lying down hurts their legs", "option_2": "So they can run away quickly if a predator approaches", "option_3": "Because they are too tall to lie down", "correct_answer": "Option_2"},
    # Story 57
    {"passage_id": 57, "question_text": "What type of fish is best for beginners?", "option_1": "Saltwater fish", "option_2": "Freshwater fish", "option_3": "Tropical fish", "correct_answer": "Option_2"},
    {"passage_id": 57, "question_text": "Why do fish tanks need a light?", "option_1": "So the fish can see at night", "option_2": "So the fish can tell the difference between night and day", "option_3": "So the water stays warm", "correct_answer": "Option_2"},
    {"passage_id": 57, "question_text": "How often should you change the water in a fish tank?", "option_1": "Every day", "option_2": "At least once a week", "option_3": "Once a month", "correct_answer": "Option_2"},
    # Story 58
    {"passage_id": 58, "question_text": "Why do the geese fly in a V shape?", "option_1": "To look beautiful", "option_2": "To make it easier on everyone else to fly behind the point", "option_3": "To confuse predators", "correct_answer": "Option_2"},
    {"passage_id": 58, "question_text": "What dangerous animal did Shane see during the migration?", "option_1": "A hawk", "option_2": "An eagle", "option_3": "A falcon", "correct_answer": "Option_2"},
    {"passage_id": 58, "question_text": "What did Greg's mom say about an exciting migration?", "option_1": "It means good weather", "option_2": "It means there are problems", "option_3": "It means they are going the right way", "correct_answer": "Option_2"},
    # Story 59
    {"passage_id": 59, "question_text": "What was Mia terrified of?", "option_1": "Dogs", "option_2": "Spiders", "option_3": "Snakes", "correct_answer": "Option_3"},
    {"passage_id": 59, "question_text": "Why did Jess really buy the snake Tiger?", "option_1": "Because she loved snakes", "option_2": "To help Mia conquer her fear", "option_3": "Because her parents gave it to her", "correct_answer": "Option_2"},
    {"passage_id": 59, "question_text": "What did Mia do with Tiger at the end?", "option_1": "She ran away from it", "option_2": "She held it in her arms", "option_3": "She asked Jess to remove it", "correct_answer": "Option_2"},
    # Story 60
    {"passage_id": 60, "question_text": "Where was Dahlia spending the summer?", "option_1": "France", "option_2": "Kyrgyzstan", "option_3": "China", "correct_answer": "Option_2"},
    {"passage_id": 60, "question_text": "Who did Dahlia unexpectedly meet at the World Nomad Games?", "option_1": "Her favorite singer", "option_2": "Her favorite YouTuber Derek Yeon", "option_3": "Her school teacher", "correct_answer": "Option_2"},
    {"passage_id": 60, "question_text": "How did Dahlia feel about Kyrgyzstan at the end of the story?", "option_1": "She still wanted to go home", "option_2": "She marveled at the countryside and looked forward to learning more", "option_3": "She was bored and unhappy", "correct_answer": "Option_2"},
]


# ════════════════════════════════
#        IMPORT FUNCTION
# ════════════════════════════════

def import_all():
    db: Session = database.SessionLocal()
    BASE_URL = os.getenv("BASE_URL", "http://127.0.0.1:8000")

    try:
        print(f"Starting import of {len(stories)} stories and {len(questions)} questions...")
        print("=" * 50)

        # Check if already imported
        existing = db.query(models.ReadingPassage).count()
        if existing > 0:
            print(f"WARNING: {existing} passages already exist in database!")
            confirm = input("Do you want to continue and add more? (yes/no): ")
            if confirm.lower() != "yes":
                print("Import cancelled.")
                return

        # Import stories
        passage_id_map = {}  # maps story id → database passage id

        for i, story in enumerate(stories):
            print(f"[{i+1}/{len(stories)}] Importing: {story['title']}...")

            # Generate TTS audio
            try:
                safe_title = story["title"].replace(" ", "_")[:20]
                audio_filename = f"passage_{safe_title}_{uuid.uuid4().hex[:8]}.mp3"
                audio_path = f"static/{audio_filename}"
                os.makedirs("static", exist_ok=True)
                text_to_speech(story["content"], audio_path)
                audio_url = f"{BASE_URL}/static/{audio_filename}"
                print(f"   ✅ Audio generated")
            except Exception as e:
                audio_url = None
                print(f"   ⚠️ Audio failed: {e}")

            # Save passage to DB
            new_passage = models.ReadingPassage(
                title=story["title"],
                content=story["content"],
                level=story["level"],
                audio_url=audio_url
            )
            db.add(new_passage)
            db.flush()  # get the id without committing

            passage_id_map[story["id"]] = new_passage.id
            print(f"   ✅ Saved to DB with id: {new_passage.id}")

        db.commit()
        print("\n✅ All stories imported successfully!")
        print("=" * 50)

        # Import questions
        print(f"\nImporting {len(questions)} questions...")
        for i, q in enumerate(questions):
            db_passage_id = passage_id_map.get(q["passage_id"])
            if not db_passage_id:
                print(f"⚠️ Passage {q['passage_id']} not found, skipping question")
                continue

            new_question = models.ReadingQuestion(
                passage_id=db_passage_id,
                question_text=q["question_text"],
                option_1=q["option_1"],
                option_2=q["option_2"],
                option_3=q["option_3"],
                correct_answer=q["correct_answer"]
            )
            db.add(new_question)

        db.commit()
        print(f"✅ All {len(questions)} questions imported successfully!")
        print("=" * 50)
        print("\n🎉 IMPORT COMPLETE!")
        print(f"   Stories: {len(stories)}")
        print(f"   Questions: {len(questions)}")
        print(f"   Level 1: 20 stories (ids 1-20)")
        print(f"   Level 2: 20 stories (ids 21-40)")
        print(f"   Level 3: 20 stories (ids 41-60)")

    except Exception as e:
        db.rollback()
        print(f"\n❌ Import failed: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    import_all()
